### ISSUE TITLE
Vulnerabilities in underlying Ruby Rake and WebBrick dependencies

### ISSUE THREAD

**Issue by ccrawford093** [pact-foundation/pact-broker-docker#29]
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [ x] Confirmed this is the right place to raise the issue - only issues related to the Dockerization of the Pact Broker should be raised here. Issues related to the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [x ] Upgraded to the latest Pact Broker Docker image OR
* [x ] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [x ] Read the [Troubleshooting](https://github.com/pact-foundation/pact-broker-docker/wiki/Troubleshooting) page

## Software versions

* **pact-broker gem version:** eg 2.58.2
* **pact-broker docker version:** eg 2.58.2.3
* **OS**: N/A
* **pact broker client details:** eg. N/A

## Expected behaviour

TBC

## Actual behaviour

When attempting to procure the latest pact broker docker image for internal use, the following OSS vulnerabilities are present in a scan of the image:

1. [CVE-2020-8130](https://github.com/advisories/GHSA-jppv-gw3r-w3q8) - There is an OS command injection vulnerability in Ruby Rake < 12.3.3 in Rake::FileList when supplying a filename that begins with the pipe character `|`.. Impacted Image File(s): /usr/local/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/file_list.rb, /usr/local/lib/ruby/gems/2.6.0/cache/rake-12.3.2.gem

  This Rake depenency was recently upgraded in pact_broker to 12.3.3 with https://github.com/pact-foundation/pact_broker/commit/9b451ee444172336b8e8278fe797009f4217c29b. However, the packaged version still seems to be at 12.3.2. Not sure if the resolution is in the dockerization or the pact_broker dependency

2. [CVE-2019-16201](https://www.ruby-lang.org/en/news/2019/10/01/webrick-regexp-digestauth-dos-cve-2019-16201/) -  WEBrick::HTTPAuth::DigestAuth in Ruby through 2.4.7, 2.5.x through 2.5.6, and 2.6.x through 2.6.4 has a regular expression Denial of Service cause by looping/backtracking. A victim must expose a WEBrick server that uses DigestAuth to the Internet or a untrusted network.. Impacted Image File(s): /usr/local/lib/ruby/2.6.0/webrick/httpauth/digestauth.rb

## Steps to reproduce

N/A

## Relevent log files

N/A

**Comment by bethesque** [comment]
I was wondering why that hadn't turned up on the normal Gihub scans, and it turns out that neither rake nor webrick are dependencies of the Pact Broker, as you can see in this [Gemfile.lock](https://github.com/pact-foundation/pact-broker-docker/blob/3639d32d5fc496d354c7986108835be2daca82e9/pact_broker/Gemfile.lock)

They're installed on the underlying image. I've been able to add some commands to the Dockerfile to remove the rake 12.0 gem, but I haven't been able to remove webrick, as it is a default gem that comes installed with Ruby. Even if I upgrade it to a later version of webrick, the original gem is not removed. I may have to try manually deleting the files.

**Comment by bethesque** [comment]
On a side note, Webrick is not actually used by the Pact Broker (as noted, it's not listed as a dependency in the Gemfile.lock). Most vulnerability scanning systems I have worked with have a way of saying "this code is not actually executed". Are you able to do that?

**Comment by bethesque** [comment]
Notes for later: https://stackoverflow.com/questions/20945110/how-can-i-remove-a-default-gem-want-to-uninstall-a-gem-1-7-7-version-of-json

**Comment by ccrawford093** [comment]
Hello, our internal scanning tool for built images does not have the ability to mark code as not executed. We could procure the image with the dependency still present, but we wouldnt be able to automate the procurement and each new version would need to be manually reviewed. If its possible to remove the WebBrick dependency that would be ideal. 

Thanks for your help

**Comment by msudeepta** [comment]
Hi @bethesque , I work with @ccrawford093 and we see the changes you referred above. Any eta to when this image would be published?

**Comment by mefellows** [comment]
The latest Ruby update should hopefully make the Webbrick one disappear based on the CVE - I was going to release this now but given all of the recent changes to GH actions I'm not sure how that process works.

I'll let Beth respond when she is back online but hopefully we'll get a release out in the next few days.

Beth - I ran the `./script/release.sh` but nothing happened (aside from a tag and travis build). It looks like the GH action responds to a manual dispatch, but wasn't sure where the right place to start. So rather than muck about, i'll wait for you and get some context from you then.

**Comment by bethesque** [comment]
I tried with the latest version of ruby 2.6, and the webrick gem version was the same. I'm not sure if it will run on ruby 2.7 or not, but I wasn't game to do it without a bunch of testing, which I don't have time to do right now. I've added a line to manually delete the files in the meantime.

The release script is `script/trigger-release.sh` Matt. You'll need to get yourself a token with public repo scope.

**Comment by mefellows** [comment]
Thanks Beth. I thought that might be the case, but also didn't want to mess with all of the GH foo you'd been doing over the past week.

**Comment by bethesque** [comment]
Try `2.58.2.4` @ccrawford093

**Comment by ccrawford093** [comment]
Scan looks good on our end with 2.58.2.4. Thanks for all the help @bethesque @mefellows

**Comment by mefellows** [comment]
Fantastic, thanks for confirming.
